spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rajat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true